### ISSUE TITLE
Strict confinement

### ISSUE THREAD

**Issue by dshcherb** [lolwww/fcbtest#3]
We need to explore adding libc-shm-shim part in order to have strict confinement working with python multiprocessing:

https://forum.snapcraft.io/t/request-for-18-track-for-libc-shm-shim-snap/8885

**Comment by dshcherb** [comment]
https://github.com/lolwww/fcbtest/pull/5

**Comment by lolwww** [comment]
Were able to push to the store as strict:
fcbtest v0.2
so resolved
